language: java
install: ./gradlew assemble

before_script:
  - sudo hostname localhost

script: ./gradlew check

notifications:
  recipients:
    - michaelklishin@me.com

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

cache:
  directories:
  - $HOME/.gradle