language: java
install: lein2 deps
script: lein2 do javac, test
notifications:
  recipients:
    - michaelklishin@me.com
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
services:
  - mongodb
addons:
  # Fix OpenJDK builds
  # https://github.com/travis-ci/travis-ci/issues/5227
  hostname: short-hostname
