language: java
install: gradle assemble

before_script:
  - sudo hostname localhost

script: gradle check

notifications:
  recipients:
    - michaelklishin@me.com

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
